name: semver-utils
author: madhead <siarhei.krukau@gmail.com>
description: One-stop shop for working with semantic versions in your workflows
inputs:
  version:
    required: true
    description: A version to process
  compare-to:
    required: false
    description: A version to compare with, if any
  satisfies:
    required: false
    description: A range to check against
outputs:
  major:
    description: Version's major number
  minor:
    description: Version's minor number
  patch:
    description: Version's patch number
  build:
    description: Version's build
  build-parts:
    description: Number of components in version's build. Individual сomponents are returned as `build-N` outputs, where an is an index from zero to `build-parts` - 1.
  prerelease:
    description: Version's pre-release
  prerelease-parts:
    description: Number of components in version's pre-release. Individual сomponents are returned as `prerelease-N` outputs, where an is an index from zero to `prerelease-parts` - 1.
  comparison-result:
    description: If the compare-to was provided, this output will contain "<" if comes after the version, ">" if it preceeds it, and "=" if they are equal
  satisfies:
    description: true if the version satisfies the given range
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: hash
  color: gray-dark
