name: Default

on:
  push:
    branches-ignore:
      - main

jobs:
  default:
    name: Default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5

      - run: npm install
      - run: npm run all

      - uses: ./
        id: test-1
        with:
          version: 1.2.3-alpha.gamma+4.5.6
      - run: '[[ "1" == "${{ steps.test-1.outputs.major }}" ]]'
      - run: '[[ "2" == "${{ steps.test-1.outputs.minor }}" ]]'
      - run: '[[ "3" == "${{ steps.test-1.outputs.patch }}" ]]'
      - run: '[[ "alpha.gamma" == "${{ steps.test-1.outputs.prerelease }}" ]]'
      - run: '[[ "2" == "${{ steps.test-1.outputs.prerelease-parts }}" ]]'
      - run: '[[ "alpha" == "${{ steps.test-1.outputs.prerelease-0 }}" ]]'
      - run: '[[ "gamma" == "${{ steps.test-1.outputs.prerelease-1 }}" ]]'
      - run: '[[ "4.5.6" == "${{ steps.test-1.outputs.build }}" ]]'
      - run: '[[ "3" == "${{ steps.test-1.outputs.build-parts }}" ]]'
      - run: '[[ "4" == "${{ steps.test-1.outputs.build-0 }}" ]]'
      - run: '[[ "5" == "${{ steps.test-1.outputs.build-1 }}" ]]'
      - run: '[[ "6" == "${{ steps.test-1.outputs.build-2 }}" ]]'

      - uses: ./
        id: test-2
        with:
          version: 1.0.0
          compare-to: 2.0.0
      - run: '[[ "<" == "${{ steps.test-2.outputs.comparison-result }}" ]]'

      - uses: ./
        id: test-3
        with:
          version: 1.2.3
          satisfies: 1.x
      - run: '[[ "true" == "${{ steps.test-3.outputs.satisfies }}" ]]'

      - uses: ./
        id: test-4
        with:
          version: 1.2.3
      - run: '[[ "2.0.0" == "${{ steps.test-4.outputs.inc-major }}" ]]'
      - run: '[[ "2.0.0-0" == "${{ steps.test-4.outputs.inc-premajor }}" ]]'
      - run: '[[ "1.3.0" == "${{ steps.test-4.outputs.inc-minor }}" ]]'
      - run: '[[ "1.3.0-0" == "${{ steps.test-4.outputs.inc-preminor }}" ]]'
      - run: '[[ "1.2.4" == "${{ steps.test-4.outputs.inc-patch }}" ]]'
      - run: '[[ "1.2.4-0" == "${{ steps.test-4.outputs.inc-prepatch }}" ]]'
      - run: '[[ "1.2.4-0" == "${{ steps.test-4.outputs.inc-prerelease }}" ]]'
