name: Default

on:
  push:
    branches-ignore:
      - main

jobs:
  default:
    name: Default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm install
      - run: npm run all

      - uses: ./
        id: test-1
        with:
          version: 1.0.0
      - run: '[[ "1" == "${{ steps.test-1.outputs.major }}" ]]'
      - run: '[[ "0" == "${{ steps.test-1.outputs.minor }}" ]]'
      - run: '[[ "0" == "${{ steps.test-1.outputs.patch }}" ]]'

      - uses: ./
        id: test-2
        with:
          version: 1.0.0
          compare-to: 2.0.0
      - run: '[[ "<" == "${{ steps.test-2.outputs.comparison-result }}" ]]'

      - uses: ./
        id: test-3
        with:
          version: 1.2.3+4.5.6
          satisfies: 1.x
      - run: '[[ "true" == "${{ steps.test-3.outputs.satisfies }}" ]]'
      - run: '[[ "4.5.6" == "${{ steps.test-3.outputs.build }}" ]]'
      - run: '[[ "3" == "${{ steps.test-3.outputs.build-parts }}" ]]'
      - run: '[[ "4" == "${{ steps.test-3.outputs.build-0 }}" ]]'
      - run: '[[ "5" == "${{ steps.test-3.outputs.build-1 }}" ]]'
      - run: '[[ "6" == "${{ steps.test-3.outputs.build-2 }}" ]]'
