name: Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_NAME: madhead
      GIT_AUTHOR_EMAIL: siarhei.krukau@gmail.com
      GIT_COMMITTER_NAME: madhead
      GIT_COMMITTER_EMAIL: siarhei.krukau@gmail.com
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.RELEASES_GITHUB_TOKEN }}

      - run: npm install
      - run: npm run all

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: dist/**

      - run: node -p "'::set-output name=version::' + require('./package.json').version"
        id: version

      - uses: ./
        id: parsedVersion
        with:
          version: ${{ steps.version.outputs.version }}

      - run: git tag --force ${{ steps.parsedVersion.outputs.major }}.${{ steps.parsedVersion.outputs.minor }}.${{ steps.parsedVersion.outputs.patch }}
      - run: git tag --force ${{ steps.parsedVersion.outputs.major }}.${{ steps.parsedVersion.outputs.minor }}
      - run: git tag --force ${{ steps.parsedVersion.outputs.major }}
      - run: git tag --force 'latest'

      - run: git push --force --tags origin
